### ISSUE TITLE
handshake failed Lib(20) Func(316) Reason(397)

### ISSUE THREAD

**Issue by gnimor** [kvic-z/pixelserv-tls#36]
I just double checked my log and I see a lot of message like:

handshake failed: client XXX.XXX.XXX.XXX:51408 server tt.onthe.io. Lib(20) Func(316) Reason(397)

and other servers. What does this really mean - is there an issue I could fix?

**Comment by kvic-z** [comment]
Lib(20) Func(316) Reason(397) are referring to some text strings specific to the OpenSSL version installed on your system. Depends on how OpenSSL is built. Some will show you the actual text. Some can't and hence the number instead.

The handshake failure (though I don't know what clients were requesting it) are expected and quite common since a few years ago. Basically advertisers & trackers found out tools (like pixelserv-tls) exist to capture what they intended to upload to their servers. Hence, they checked the server certificates. Once they realized the cert was not one of their own, they disconnected abruptly or aborted handshake in some other ways.

Such statistics are captured in the counters on /servstats page. Check out e.g. cls, cly that are usually caused by the above reason.
