### ISSUE TITLE
Install on Debian 9

### ISSUE THREAD

**Issue by asterriya** [kvic-z/pixelserv-tls#40]
Did someone know how to install pixelserv on Debian 9/10? I didn't find anywhere instructions for this. Also, I'm interest if there is option to make whitelist/blacklist and add custom ads list's to pixelserv? And how to make it work if I'm already have pi-hole/adguard? Is that possible to make pixelserv work on 53 port?

**Comment by kvic-z** [comment]
For Debian (any versions), as far as I'm aware but I could be out of the loop for a while, there is no one maintaining a Debian package of pixelserv-tls. To get it up and running is simple because pixelserv-tls is itself very simple. You can simply go with the route "Build from Source" in the README.md. 

There is a FAQ in the Wiki section outlining how to configure Pi-Hole to work with pixelserv-tls. Beware that the info there might be a couple of years out of date. Pls let me know if that FAQ still helps or you found what's out of date. Cheers.
